# Generated by Django 5.2.3 on 2025-06-17 04:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Optional description for the shortened URL', null=True)),
                ('original_url', models.URLField(help_text='The original URL to be shortened', max_length=2048)),
                ('short_code', models.CharField(db_index=True, help_text='Generated short code using a-zA-Z0-9 characters in consecutive order', max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the URL was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the URL was last updated')),
            ],
            options={
                'verbose_name': 'Short URL',
                'verbose_name_plural': 'Short URLs',
                'db_table': 'short_urls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UrlVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the URL was visited')),
                ('visitor_signature', models.CharField(db_index=True, help_text="SHA256 hash of visitor's browser fingerprint for unique visitor tracking", max_length=64)),
                ('short_url', models.ForeignKey(help_text='Reference to the shortened URL that was visited', on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='shortener.shorturl')),
            ],
            options={
                'verbose_name': 'URL Visit',
                'verbose_name_plural': 'URL Visits',
                'db_table': 'url_visits',
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['short_url', 'visitor_signature'], name='url_visits_short_u_3147cb_idx'), models.Index(fields=['visited_at'], name='url_visits_visited_9085fc_idx')],
            },
        ),
    ]
