# Generated by Django 5.2.3 on 2025-08-19 06:48

import shortener.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR code image for the shortened URL', null=True, upload_to=shortener.models.qr_image_upload_path),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='short_code',
            field=models.CharField(db_index=True, help_text='Generated short code using a-zA-Z0-9\\-_ characters in consecutive order', max_length=40, unique=True),
        ),
    ]
